name:  "Run Tests"
on: [push]
permissions:
  contents: write
jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: git checkout of loopback
        id: git_checkout_lb
        shell: bash
        run: |
          ./start-test.sh
        continue-on-error: false