name:  "Run Tests"
on: [push]
jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        id: poc_apply
        shell: bash
        run: |
          ls
        continue-on-error: false